# Add a RabbitMQ service
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=master123
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  rabbit_data:
    driver: local
