apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gw-deploy
  labels:
    app: api-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gw
  template:
    metadata:
      labels:
        app: api-gw
    spec:
      containers:
      - name: api-gw
        image: api-gateway:v1.4
        envFrom:
        - configMapRef:
            name: app-config
