apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gw
  name: api-gw-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: api-gw
  type: NodePort
